### ISSUE TITLE
Authentication problem with firebase (I want the user to be able to sign in  and register with firebase access tokens), also create design for laptops and mobiles

### ISSUE THREAD

**Issue by Riqui87887** [Riqui87887/amazonCopy#1]
Authentication problem with firebase (I want the user to be able to sign in and register with firebase access tokens), also create design for laptops and mobiles.
Discuss details in DM

**Comment by Anna719** [comment]
Hi! Can i work on this project? Thanks:)

**Comment by Riqui87887** [comment]
> Hi! Can i work on this project? Thanks:)

Sure
